setwd("/project/voight_datasets/blood/thomc/GREGOR-results/GREGOR-results_150924_ENCODE.GiegerPruned_10Knbr/")
Sys.sleep(2)
z <- read.table(file="150925_AllENCODE_Giegersnps_Mined.txt", header=T)
Sys.sleep(15)
library(glmnet)
Sys.sleep(2)
sink("160222.GLMnet_Lasso_Rcode_AllExcept259.columns_run.txt") #Note that column 259 was corrupted, hence left out of analysis
cat("\nnrow: ")
nrow(z)
cat("ncol: ")
ncol(z)
x <- data.matrix(z[,c(2,4,5,6:258,260:634)])
y <- data.matrix(z[,3])
pfactor = matrix(nrow = 1, ncol = 631)
pfactor[1,] = 1
pfactor[1,c(1:3)] = 0
cvfit = cv.glmnet(x, y, penalty.factor = pfactor, family = "binomial", type.measure = "auc")
Sys.sleep(15)
cat("print(cvfit)\n")
print(cvfit)
cat("coef(cvfit, s=lambda.1se)\n")
coef(cvfit, s="lambda.1se")
cat("coef(cvfit, s=lambda.min)\n")
coef(cvfit, s="lambda.min")
cat("AUC saved as 160222.631.factors.AllExcept259.AUCplot.pdf\n")
pdf("160222.631.factors.AllExcept259.AUCplot.pdf")
plot(cvfit)
dev.off()
savehistory(file="Routput.Rhistory")
save.image("script-output.RData")
cat("Script completed\n\n")
sink()
detach("package:glmnet")
q()
