setwd("/project/voight_ML/thomc/thomc_results/GREGOR-results/GREGOR-results.180822.AstlePLT.BROADpaulTIJSSEN/")
Sys.sleep(2)
z <- read.table(file="181101.AstlePLT.BROADpaulTIJSSEN.Mined.NbrMAFgt10.Shuf58000.cat", header=T)
Sys.sleep(15)
library(glmnet)
Sys.sleep(2)
sink("190808.GLMnet_Lasso_Rcode_862.columns.NbrMAFgt10_run17")
cat("\nnrow: ")
nrow(z)
cat("ncol: ")
ncol(z)
x <- data.matrix(z[,c(2,4,5,14:17,19,32:729,731:887)]) #column 5 is MAF
y <- data.matrix(z[,3])
pfactor = matrix(nrow = 1, ncol = 865)
pfactor[1,] = 1
pfactor[1,c(1:3)] = 0 #this is c1:2 when excluding MAF, used to be c(1:3) when it included MAF
cvfit = cv.glmnet(x, y, penalty.factor = pfactor, family = "binomial", type.measure = "auc")
Sys.sleep(15)
cat("print(cvfit)\n")
print(cvfit)
cat("coef(cvfit, s=lambda.1se)\n")
coef(cvfit, s="lambda.1se")
cat("coef(cvfit, s=lambda.min)\n")
coef(cvfit, s="lambda.min")
#cat("cvm$lambda.min\n")
#print(cvm$lambda.min)
#cat("cvm$lambda.1se\n")
#cvm$lambda.1se
cat("AUC saved as 190808.AstlePLT.865.factors.NbrMAFgt10.run17.AUCplot.pdf\n")
pdf("190808.AstlePLT.865.factors.run17.AUCplot.pdf")
plot(cvfit)
dev.off()
savehistory(file="Routput.Rhistory")
save.image("script-output.RData")
cat("Script completed\n\n")
sink()
detach("package:glmnet")
q()
